spring:
  application:
    name: course-service
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: 129.211.26.164:8848
      username: nacos  # 也可以放在顶层
      password: nacos
      discovery:
        namespace: 61728b3c-2f54-4912-99d4-b7b283fad8f7
        group: course-service
      config:
        namespace: 61728b3c-2f54-4912-99d4-b7b283fad8f7
        group: course-service
        file-extension: yaml
        refresh-enabled: true
  config:
    import: nacos:course-service-${spring.profiles.active}.yaml

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 默认就是 true，开启驼峰命名映射