spring:
  application:
    name: gateway-service
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: 129.211.26.164:8848
      username: nacos  # 也可以放在顶层
      password: nacos
      discovery:
        namespace: 61728b3c-2f54-4912-99d4-b7b283fad8f7
        group: gateway-service
      config:
        namespace: 61728b3c-2f54-4912-99d4-b7b283fad8f7
        group: gateway-service
        file-extension: yaml
        refresh-enabled: true
        shared-configs:
          - data-id: mybatis-plus-${spring.profiles.active}.yaml
            group: common-module
            refresh: true
  config:
    import: nacos:gateway-service-${spring.profiles.active}.yaml