server:
  port: 8001
spring:
  datasource:
    url: jdbc:mysql://139.196.111.59:13306/edux_media?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: edux
    password: edux@2025
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 默认就是 true，开启驼峰命名映射